name: Simple CI

on:
  pull_request:
    branches:
        -develop
    types: [closed]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v35
    - name: Get changed lang files
      id: lang-files
      run: echo "all=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -oE 'lang\/\S+' | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
    - run: npm install
    - name: Check git status
      run: git status
    - name: Normalize lang files to ensure sorted
      if: steps.lang-files.outputs.all
      run: npm run lang-sort
    - name: Check lang files are formatted correctly
      if: steps.lang-files.outputs.all
      run: npm run lint:lang
    - name: Check if the git repository is clean
      run: $(exit $(git status --porcelain --untracked-files=no | head -255 | wc -l)) || (echo "Dirty git tree"; git diff; exit 1)
    - run: npm run lint:ci && npm run tsc:ci
  linux-build:
    name: Build Frontend (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - run: make

  deploy:
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest
        needs: linux-build
        steps:
          - name: Deploy iSpeaker Jitsi Meeting
            uses: appleboy/ssh-action@v0.1.4
            with:
              host: ${{ secrets.SSH_HOST }}
              key: ${{ secrets.SSH_KEY }}
              username: ${{ secrets.SSH_USER }}

              script: |
                cd /var/www/ispeaker/staging/jitsi-meet
                git reset --hard
                git switch develop
                git pull origin develop
                npm install
                npm run tsc:web